spring.application.name=inventario

# 1. Credenciales de PostgreSQL (coinciden con tu .env)
spring.datasource.url=jdbc:postgresql://localhost:5433/introInventario_db
spring.datasource.username=introInventario
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate (El motor que traduce Java a SQL)
# 'update' crea las tablas automáticamente si no existen, basado en tus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Opcional: Formatea el SQL en consola para que sea más fácil de leer
spring.jpa.properties.hibernate.format_sql=true